export const announcementConstants = {

    ANNOUNCEMENTS_GETALL_REQUEST: 'ANNOUNCEMENTS_GETALL_REQUEST',
    ANNOUNCEMENTS_GETALL_SUCCESS: 'ANNOUNCEMENTS_GETALL_SUCCESS',
    ANNOUNCEMENTS_GETALL_FAILURE: 'ANNOUNCEMENTS_GETALL_FAILURE',

    ANNOUNCEMENTS_GETNEWEST_REQUEST: 'ANNOUNCEMENTS_GETNEWEST_REQUEST',
    ANNOUNCEMENTS_GETNEWEST_SUCCESS: 'ANNOUNCEMENTS_GETNEWEST_SUCCESS',
    ANNOUNCEMENTS_GETNEWEST_FAILURE: 'ANNOUNCEMENTS_GETNEWEST_FAILURE',

    ANNOUNCEMENTS_GETBYID_REQUEST: 'ANNOUNCEMENTS_GETBYID_REQUEST',
    ANNOUNCEMENTS_GETBYID_SUCCESS: 'ANNOUNCEMENTS_GETBYID_SUCCESS',
    ANNOUNCEMENTS_GETBYID_FAILURE: 'ANNOUNCEMENTS_GETBYID_FAILURE',
    
    ANNOUNCEMENTS_INSERT_REQUEST: 'ANNOUNCEMENTS_INSERT_REQUEST',
    ANNOUNCEMENTS_INSERT_SUCCESS: 'ANNOUNCEMENTS_INSERT_SUCCESS',
    ANNOUNCEMENTS_INSERT_FAILURE: 'ANNOUNCEMENTS_INSERT_FAILURE',

    ANNOUNCEMENTS_UPDATE_REQUEST: 'ANNOUNCEMENTS_UPDATE_REQUEST',
    ANNOUNCEMENTS_UPDATE_SUCCESS: 'ANNOUNCEMENTS_UPDATE_SUCCESS',
    ANNOUNCEMENTS_UPDATE_FAILURE: 'ANNOUNCEMENTS_UPDATE_FAILURE',

    ANNOUNCEMENTS_FILTER_REQUEST: 'ANNOUNCEMENTS_FILTER_REQUEST',
    ANNOUNCEMENTS_FILTER_SUCCESS: 'ANNOUNCEMENTS_FILTER_SUCCESS',
    ANNOUNCEMENTS_FILTER_FAILURE: 'ANNOUNCEMENTS_FILTER_FAILURE',
};
