export const classConstants = {
    MEMBER_TYPE_IS_MEMBER: 1,
    MEMBER_TYPE_IS_TEACHER: 10,

    STATUS_OF_USER_IN_CLASS: {
      SEND_REQUEST_JOIN: "send_request_join",
      JOINED: 'joined',
      NOT_RELATE: 'not_relate'
    },

    DEFAULT_ALL_TOPIC: 'all_topic',
    DEFAULT_ALL_STUDENT: 'all_student',

    POST_SCOPE_TYPE:{
        PROTECTED: '10',
        PRIVATE: '100'
    },

    CLASSES_GETALL_REQUEST: 'CLASSES_GETALL_REQUEST',
    CLASSES_GETALL_SUCCESS: 'CLASSES_GETALL_SUCCESS',
    CLASSES_GETALL_FAILURE: 'CLASSES_GETALL_FAILURE',

    CLASSES_GETBYID_REQUEST: 'CLASSES_GETBYID_REQUEST',
    CLASSES_GETBYID_SUCCESS: 'CLASSES_GETBYID_SUCCESS',
    CLASSES_GETBYID_FAILURE: 'CLASSES_GETBYID_FAILURE',

    // CLASSES_GETBYUSERID_REQUEST: 'CLASSES_GETBYUSERID_REQUEST',
    // CLASSES_GETBYUSERID_SUCCESS: 'CLASSES_GETBYUSERID_SUCCESS',
    // CLASSES_GETBYUSERID_FAILURE: 'CLASSES_GETBYUSERID_FAILURE',

    CLASSES_GETMEMBERS_REQUEST: 'CLASSES_GETMEMBERS_REQUEST',
    CLASSES_GETMEMBERS_SUCCESS: 'CLASSES_GETMEMBERS_SUCCESS',
    CLASSES_GETMEMBERS_FAILURE: 'CLASSES_GETMEMBERS_FAILURE',

    CLASSES_GETREQUESTS_REQUEST: 'CLASSES_GETREQUESTS_REQUEST',
    CLASSES_GETREQUESTS_SUCCESS: 'CLASSES_GETREQUESTS_SUCCESS',
    CLASSES_GETREQUESTS_FAILURE: 'CLASSES_GETREQUESTS_FAILURE',

    CLASSES_GETFILES_REQUEST: 'CLASSES_GETFILES_REQUEST',
    CLASSES_GETFILES_SUCCESS: 'CLASSES_GETFILES_SUCCESS',
    CLASSES_GETFILES_FAILURE: 'CLASSES_GETFILES_FAILURE',

    CLASSES_GETPOSTS_REQUEST: 'CLASSES_GETPOSTS_REQUEST',
    CLASSES_GETPOSTS_SUCCESS: 'CLASSES_GETPOSTS_SUCCESS',
    CLASSES_GETPOSTS_FAILURE: 'CLASSES_GETPOSTS_FAILURE',

    CLASSES_GETPOSTSBYUSER_REQUEST: 'CLASSES_GETPOSTSBYUSER_REQUEST',
    CLASSES_GETPOSTSBYUSER_SUCCESS: 'CLASSES_GETPOSTSBYUSER_SUCCESS',
    CLASSES_GETPOSTSBYUSER_FAILURE: 'CLASSES_GETPOSTSBYUSER_FAILURE',

    CLASSES_GETPOSTSBYTOPIC_REQUEST: 'CLASSES_GETPOSTSBYTOPIC_REQUEST',
    CLASSES_GETPOSTSBYTOPIC_SUCCESS: 'CLASSES_GETPOSTSBYTOPIC_SUCCESS',
    CLASSES_GETPOSTSBYTOPIC_FAILURE: 'CLASSES_GETPOSTSBYTOPIC_FAILURE',

    CLASSES_GETEVENTS_REQUEST: 'CLASSES_GETEVENTS_REQUEST',
    CLASSES_GETEVENTS_SUCCESS: 'CLASSES_GETEVENTS_SUCCESS',
    CLASSES_GETEVENTS_FAILURE: 'CLASSES_GETEVENTS_FAILURE',

    CLASSES_GETEVENTSBYUSER_REQUEST: 'CLASSES_GETEVENTSBYUSER_REQUEST',
    CLASSES_GETEVENTSBYUSER_SUCCESS: 'CLASSES_GETEVENTSBYUSER_SUCCESS',
    CLASSES_GETEVENTSBYUSER_FAILURE: 'CLASSES_GETEVENTSBYUSER_FAILURE',

    CLASSES_GETTOPICS_REQUEST: 'CLASSES_GETTOPICS_REQUEST',
    CLASSES_GETTOPICS_SUCCESS: 'CLASSES_GETTOPICS_SUCCESS',
    CLASSES_GETTOPICS_FAILURE: 'CLASSES_GETTOPICS_FAILURE',

    CLASSES_INSERT_REQUEST: 'CLASSES_INSERT_REQUEST',
    CLASSES_INSERT_SUCCESS: 'CLASSES_INSERT_SUCCESS',
    CLASSES_INSERT_FAILURE: 'CLASSES_INSERT_FAILURE',

    CLASSES_UPDATE_REQUEST: 'CLASSES_UPDATE_REQUEST',
    CLASSES_UPDATE_SUCCESS: 'CLASSES_UPDATE_SUCCESS',
    CLASSES_UPDATE_FAILURE: 'CLASSES_UPDATE_FAILURE',

    CLASSES_INSERTPOST_REQUEST: 'CLASSES_INSERTPOST_REQUEST',
    CLASSES_INSERTPOST_SUCCESS: 'CLASSES_INSERTPOST_SUCCESS',
    CLASSES_INSERTPOST_FAILURE: 'CLASSES_INSERTPOST_FAILURE',

    CLASSES_GETCOMMENTS_REQUEST: 'CLASSES_GETCOMMENTS_REQUEST',
    CLASSES_GETCOMMENTS_SUCCESS: 'CLASSES_GETCOMMENTS_SUCCESS',
    CLASSES_GETCOMMENTS_FAILURE: 'CLASSES_GETCOMMENTS_FAILURE',

    CLASSES_INSERTCOMMENT_REQUEST: 'CLASSES_INSERTCOMMENT_REQUEST',
    CLASSES_INSERTCOMMENT_SUCCESS: 'CLASSES_INSERTCOMMENT_SUCCESS',
    CLASSES_INSERTCOMMENT_FAILURE: 'CLASSES_INSERTCOMMENT_FAILURE',

    CLASSES_GETFAVOURITES_REQUEST: 'CLASSES_GETFAVOURITES_REQUEST',
    CLASSES_GETFAVOURITES_SUCCESS: 'CLASSES_GETFAVOURITES_SUCCESS',
    CLASSES_GETFAVOURITES_FAILURE: 'CLASSES_GETFAVOURITES_FAILURE',

    CLASSES_INSERTFAVOURITES_REQUEST: 'CLASSES_INSERTFAVOURITES_REQUEST',
    CLASSES_INSERTFAVOURITES_SUCCESS: 'CLASSES_INSERTFAVOURITES_SUCCESS',
    CLASSES_INSERTFAVOURITES_FAILURE: 'CLASSES_INSERTFAVOURITES_FAILURE',

    CLASSES_DELETEFAVOURITE_REQUEST: 'CLASSES_DELETEFAVOURITE_REQUEST',
    CLASSES_DELETEFAVOURITE_SUCCESS: 'CLASSES_DELETEFAVOURITE_SUCCESS',
    CLASSES_DELETEFAVOURITE_FAILURE: 'CLASSES_DELETEFAVOURITE_FAILURE',

    CLASSES_UPDATEPOSTINFO_SUCCESS: 'CLASSES_UPDATEPOSTINFO_SUCCESS'
};
