export const classConstants = {
    CLASSES_GETALL_REQUEST: 'CLASSES_GETALL_REQUEST',
    CLASSES_GETALL_SUCCESS: 'CLASSES_GETALL_SUCCESS',
    CLASSES_GETALL_FAILURE: 'CLASSES_GETALL_FAILURE',

    CLASSES_GETBYID_REQUEST: 'CLASSES_GETBYID_REQUEST',
    CLASSES_GETBYID_SUCCESS: 'CLASSES_GETBYID_SUCCESS',
    CLASSES_GETBYID_FAILURE: 'CLASSES_GETBYID_FAILURE',

    CLASSES_GETBYUSERID_REQUEST: 'CLASSES_GETBYUSERID_REQUEST',
    CLASSES_GETBYUSERID_SUCCESS: 'CLASSES_GETBYUSERID_SUCCESS',
    CLASSES_GETBYUSERID_FAILURE: 'CLASSES_GETBYUSERID_FAILURE',

    CLASSES_GETMEMBERS_REQUEST: 'CLASSES_GETMEMBERS_REQUEST',
    CLASSES_GETMEMBERS_SUCCESS: 'CLASSES_GETMEMBERS_SUCCESS',
    CLASSES_GETMEMBERS_FAILURE: 'CLASSES_GETMEMBERS_FAILURE',

    CLASSES_GETREQUESTS_REQUEST: 'CLASSES_GETREQUESTS_REQUEST',
    CLASSES_GETREQUESTS_SUCCESS: 'CLASSES_GETREQUESTS_SUCCESS',
    CLASSES_GETREQUESTS_FAILURE: 'CLASSES_GETREQUESTS_FAILURE',

    CLASSES_GETFILES_REQUEST: 'CLASSES_GETFILES_REQUEST',
    CLASSES_GETFILES_SUCCESS: 'CLASSES_GETFILES_SUCCESS',
    CLASSES_GETFILES_FAILURE: 'CLASSES_GETFILES_FAILURE',

    CLASSES_INSERT_REQUEST: 'CLASSES_INSERT_REQUEST',
    CLASSES_INSERT_SUCCESS: 'CLASSES_INSERT_SUCCESS',
    CLASSES_INSERT_FAILURE: 'CLASSES_INSERT_FAILURE',

    CLASSES_UPDATE_REQUEST: 'CLASSES_UPDATE_REQUEST',
    CLASSES_UPDATE_SUCCESS: 'CLASSES_UPDATE_SUCCESS',
    CLASSES_UPDATE_FAILURE: 'CLASSES_UPDATE_FAILURE',
};
