export const eventConstants = {
    EVENTS_GETALL_REQUEST: 'EVENTS_GETALL_REQUEST',
    EVENTS_GETALL_SUCCESS: 'EVENTS_GETALL_SUCCESS',
    EVENTS_GETALL_FAILURE: 'EVENTS_GETALL_FAILURE',

    EVENTS_GETBYID_REQUEST: 'EVENTS_GETBYID_REQUEST',
    EVENTS_GETBYID_SUCCESS: 'EVENTS_GETBYID_SUCCESS',
    EVENTS_GETBYID_FAILURE: 'EVENTS_GETBYID_FAILURE',

    EVENTS_INSERT_REQUEST: 'EVENTS_INSERT_REQUEST',
    EVENTS_INSERT_SUCCESS: 'EVENTS_INSERT_SUCCESS',
    EVENTS_INSERT_FAILURE: 'EVENTS_INSERT_FAILURE',

    EVENTS_UPDATE_REQUEST: 'EVENTS_UPDATE_REQUEST',
    EVENTS_UPDATE_SUCCESS: 'EVENTS_UPDATE_SUCCESS',
    EVENTS_UPDATE_FAILURE: 'EVENTS_UPDATE_FAILURE',
};
