export const eventConstants = {
    EVENT_CONTEXT:{
      USER: '1',
      GROUP: '10',
      SYSTEM: '100'
    },

    EVENTS_GETALL_REQUEST: 'EVENTS_GETALL_REQUEST',
    EVENTS_GETALL_SUCCESS: 'EVENTS_GETALL_SUCCESS',
    EVENTS_GETALL_FAILURE: 'EVENTS_GETALL_FAILURE',

    EVENTS_GETNOTBELONGCLASS_REQUEST: 'EVENTS_GETNOTBELONGCLASS_REQUEST',
    EVENTS_GETNOTBELONGCLASS_SUCCESS: 'EVENTS_GETNOTBELONGCLASS_SUCCESS',
    EVENTS_GETNOTBELONGCLASS_FAILURE: 'EVENTS_GETNOTBELONGCLASS_FAILURE',

    EVENTS_GETUPCOMMING_REQUEST: 'EVENTS_GETUPCOMMING_REQUEST',
    EVENTS_GETUPCOMMING_SUCCESS: 'EVENTS_GETUPCOMMING_SUCCESS',
    EVENTS_GETUPCOMMING_FAILURE: 'EVENTS_GETUPCOMMING_FAILURE',

    EVENTS_GETBYUSER_REQUEST: 'EVENTS_GETBYUSER_REQUEST',
    EVENTS_GETBYUSER_SUCCESS: 'EVENTS_GETBYUSER_SUCCESS',
    EVENTS_GETBYUSER_FAILURE: 'EVENTS_GETBYUSER_FAILURE',

    EVENTS_GETBYCLASS_REQUEST: 'EVENTS_GETBYCLASS_REQUEST',
    EVENTS_GETBYCLASS_SUCCESS: 'EVENTS_GETBYCLASS_SUCCESS',
    EVENTS_GETBYCLASS_FAILURE: 'EVENTS_GETBYCLASS_FAILURE',

    EVENTS_FILTER_REQUEST: 'EVENTS_FILTER_REQUEST',
    EVENTS_FILTER_SUCCESS: 'EVENTS_FILTER_SUCCESS',
    EVENTS_FILTER_FAILURE: 'EVENTS_FILTER_FAILURE',

    EVENTS_GETBYID_REQUEST: 'EVENTS_GETBYID_REQUEST',
    EVENTS_GETBYID_SUCCESS: 'EVENTS_GETBYID_SUCCESS',
    EVENTS_GETBYID_FAILURE: 'EVENTS_GETBYID_FAILURE',

    EVENTS_INSERT_REQUEST: 'EVENTS_INSERT_REQUEST',
    EVENTS_INSERT_SUCCESS: 'EVENTS_INSERT_SUCCESS',
    EVENTS_INSERT_FAILURE: 'EVENTS_INSERT_FAILURE',

    EVENTS_UPDATE_REQUEST: 'EVENTS_UPDATE_REQUEST',
    EVENTS_UPDATE_SUCCESS: 'EVENTS_UPDATE_SUCCESS',
    EVENTS_UPDATE_FAILURE: 'EVENTS_UPDATE_FAILURE',
};
