export const postConstants = {
    SCOPETYPE:{
        IS_PROTECTED: '10',
        IS_PRIVATE: '100'
    },

    CONTEXT_VIEW:{
        IN_HOME_PAGE: '1',
        IN_USER_PAGE: '2',
        IN_CLASS_PAGE: '3',
    },

    POSTS_GETCOMMENTS_REQUEST: 'POSTS_GETCOMMENTS_REQUEST',
    POSTS_GETCOMMENTS_SUCCESS: 'POSTS_GETCOMMENTS_SUCCESS',
    POSTS_GETCOMMENTS_FAILURE: 'POSTS_GETCOMMENTS_FAILURE',
}