export const postConstants = {
    SCOPETYPE:{
        IS_PROTECTED: '10',
        IS_PRIVATE: '100'
    },

    POSTS_GETCOMMENTS_REQUEST: 'POSTS_GETCOMMENTS_REQUEST',
    POSTS_GETCOMMENTS_SUCCESS: 'POSTS_GETCOMMENTS_SUCCESS',
    POSTS_GETCOMMENTS_FAILURE: 'POSTS_GETCOMMENTS_FAILURE',
}