export const postConstants = {
    SCOPETYPE:{
        IS_PROTECTED: '10',
        IS_PRIVATE: '100'
    },

    CONTEXT_VIEW:{
        IN_HOME_PAGE: '1',
        IN_USER_PAGE: '2',
        IN_CLASS_PAGE: '3',
    },

    POSTS_INSERTCOMMENT_REQUEST: 'POSTS_INSERTCOMMENT_REQUEST',
    POSTS_INSERTCOMMENT_SUCCESS: 'POSTS_INSERTCOMMENT_SUCCESS',
    POSTS_INSERTCOMMENT_FAILURE: 'POSTS_INSERTCOMMENT_FAILURE',

    POSTS_INSERTFAVOURITE_REQUEST: 'POSTS_INSERTFAVOURITE_REQUEST',
    POSTS_INSERTFAVOURITE_SUCCESS: 'POSTS_INSERTFAVOURITE_SUCCESS',
    POSTS_INSERTFAVOURITE_FAILURE: 'POSTS_INSERTFAVOURITE_FAILURE',

    POSTS_DELETEFAVOURITE_REQUEST: 'POSTS_DELETEFAVOURITE_REQUEST',
    POSTS_DELETEFAVOURITE_SUCCESS: 'POSTS_DELETEFAVOURITE_SUCCESS',
    POSTS_DELETEFAVOURITE_FAILURE: 'POSTS_DELETEFAVOURITE_FAILURE',

    POSTS_UPDATEPOSTINFO_REQUEST: 'POSTS_UPDATEPOSTINFO_REQUEST',
    POSTS_UPDATEPOSTINFO_SUCCESS: 'POSTS_UPDATEPOSTINFO_SUCCESS',
    POSTS_UPDATEPOSTINFO_FAILURE: 'POSTS_UPDATEPOSTINFO_FAILURE',

    // POSTS_USERS_GETPOSTS_REQUEST: 'POSTS_USERS_GETPOSTS_REQUEST',
    // POSTS_USERS_GETPOSTS_SUCCESS: 'POSTS_USERS_GETPOSTS_SUCCESS',
    // POSTS_USERS_GETPOSTS_FAILURE: 'USERS_GETPOSTS_FAILURE',
    //
    // POSTS_CLASSES_GETPOSTSBYUSER_REQUEST: 'POSTS_CLASSES_GETPOSTSBYUSER_REQUEST',
    // POSTS_CLASSES_GETPOSTSBYUSER_SUCCESS: 'POSTS_CLASSES_GETPOSTSBYUSER_SUCCESS',
    // POSTS_CLASSES_GETPOSTSBYUSER_FAILURE: 'POSTS_CLASSES_GETPOSTSBYUSER_FAILURE',
    //
    // POSTS_CLASSES_GETPOSTSBYTOPIC_REQUEST: 'POSTS_CLASSES_GETPOSTSBYTOPIC_REQUEST',
    // POSTS_CLASSES_GETPOSTSBYTOPIC_SUCCESS: 'POSTS_CLASSES_GETPOSTSBYTOPIC_SUCCESS',
    // POSTS_CLASSES_GETPOSTSBYTOPIC_FAILURE: 'POSTS_CLASSES_GETPOSTSBYTOPIC_FAILURE',
}