export const userConstants = {
    TYPE_USER_IS_NORMAL: '0',
    TYPE_USER_IS_TEACHER: '10',
    TYPE_USER_IS_SYSTEM: '100',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    USERS_GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    USERS_GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    USERS_GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    USERS_GETBYID_REQUEST: 'USERS_GETBYID_REQUEST',
    USERS_GETBYID_SUCCESS: 'USERS_GETBYID_SUCCESS',
    USERS_GETBYID_FAILURE: 'USERS_GETBYID_FAILURE',

    USERS_UPDATEPROFILEPICTURE_REQUEST: 'USERS_UPDATEPROFILEPICTURE_REQUEST',
    USERS_UPDATEPROFILEPICTURE_SUCCESS: 'USERS_UPDATEPROFILEPICTURE_SUCCESS',
    USERS_UPDATEPROFILEPICTURE_FAILURE: 'USERS_UPDATEPROFILEPICTURE_FAILURE',

    USERS_UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    USERS_UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    USERS_UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    USERS_GETCLASSJOINED_REQUEST: 'USERS_GETCLASSJOINED_REQUEST',
    USERS_GETCLASSJOINED_SUCCESS: 'USERS_GETCLASSJOINED_SUCCESS',
    USERS_GETCLASSJOINED_FAILURE: 'USERS_GETCLASSJOINED_FAILURE',

    USERS_GETCLASSREQUEST_REQUEST: 'USERS_GETCLASSREQUEST_REQUEST',
    USERS_GETCLASSREQUEST_SUCCESS: 'USERS_GETCLASSREQUEST_SUCCESS',
    USERS_GETCLASSREQUEST_FAILURE: 'USERS_GETCLASSREQUEST_FAILURE',

    USERS_UPDATESTATUSOFCLASS_REQUEST: 'USERS_UPDATESTATUSOFCLASS_REQUEST',
    USERS_UPDATESTATUSOFCLASS_SENTREQUEST_SUCCESS: 'USERS_UPDATESTATUSOFCLASS_SENTREQUEST_SUCCESS',
    USERS_UPDATESTATUSOFCLASS_JOINED_SUCCESS: 'USERS_UPDATESTATUSOFCLASS_JOINED_SUCCESS',
    USERS_UPDATESTATUSOFCLASS_FAILURE: 'USERS_UPDATESTATUSOFCLASS_FAILURE',

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'

    USERS_GETPOSTS_REQUEST: 'USERS_GETPOSTS_REQUEST',
    USERS_GETPOSTS_SUCCESS: 'USERS_GETPOSTS_SUCCESS',
    USERS_GETPOSTS_FAILURE: 'USERS_GETPOSTS_FAILURE',
};
